#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OVERRIDE_FILE="docker-compose.override.yml"
TEMPLATE_FILE="docker-compose.override.nvidia.yml"

has_nvidia_gpu() {
  if [[ -e /dev/nvidia0 ]]; then
    return 0
  fi
  if command -v nvidia-smi >/dev/null 2>&1; then
    if nvidia-smi -L 2>/dev/null | grep -q 'GPU '; then
      return 0
    fi
  fi
  return 1
}

has_nvidia_toolkit() {
  if docker info 2>/dev/null | grep -qi 'nvidia'; then
    return 0
  fi
  if command -v nvidia-ctk >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

resolve_host_lib() {
  local pattern="$1"
  ldconfig -p 2>/dev/null | awk -v pat="$pattern" '$1 ~ pat { print $NF; exit }'
}

collect_nvidia_vulkan_mounts() {
  MOUNT_LINES=()
  declare -A seen=()

  add_mount() {
    local host_path="$1"
    local container_path="${2:-$1}"
    [[ -f "$host_path" ]] || return 0
    local key="${host_path}:${container_path}"
    [[ -n "${seen[$key]:-}" ]] && return 0
    seen[$key]=1
    MOUNT_LINES+=("      - ${host_path}:${container_path}:ro")
  }

  for icd in /usr/share/vulkan/icd.d/nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json; do
    add_mount "$icd"
  done

  local lib_patterns=(
    'libGLX_nvidia\.so\.0'
    'libEGL_nvidia\.so\.0'
    'libnvidia-glcore\.so'
    'libnvidia-glvkspirv\.so'
    'libnvidia-eglcore\.so'
    'libnvidia-glsi\.so'
    'libnvidia-gpucomp\.so'
    'libnvidia-allocator\.so'
  )

  local pattern lib_path
  for pattern in "${lib_patterns[@]}"; do
    lib_path="$(resolve_host_lib "$pattern")"
    add_mount "$lib_path"
  done
}

write_override() {
  collect_nvidia_vulkan_mounts

  if [[ ${#MOUNT_LINES[@]} -eq 0 ]]; then
    echo "ERROR: Could not find nvidia_icd.json or NVIDIA GL libraries on the host." >&2
    echo "Install the NVIDIA driver with Vulkan support, then re-run this script." >&2
    echo "Check on the host: ls /usr/share/vulkan/icd.d/nvidia_icd.json" >&2
    exit 1
  fi

  local has_icd=0
  for icd in /usr/share/vulkan/icd.d/nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json; do
    [[ -f "$icd" ]] && has_icd=1
  done
  if [[ "$has_icd" -eq 0 ]]; then
    echo "WARNING: nvidia_icd.json not found on host; mounting GL libraries only." >&2
    echo "Vulkan may still fail until the driver Vulkan package is installed." >&2
  fi

  {
    echo "# Auto-generated by scripts/configure-gpu-compose.sh — do not edit"
    tail -n +2 "$TEMPLATE_FILE"
    echo "    volumes:"
    printf '%s\n' "${MOUNT_LINES[@]}"
  } >"$OVERRIDE_FILE"
}

if has_nvidia_gpu; then
  if has_nvidia_toolkit; then
    if [[ ! -f "$TEMPLATE_FILE" ]]; then
      echo "ERROR: Missing $TEMPLATE_FILE" >&2
      exit 1
    fi
    write_override
    echo "NVIDIA GPU detected. Wrote $OVERRIDE_FILE for GPU passthrough."
    echo "  (${#MOUNT_LINES[@]} host Vulkan/GL bind mount(s) added)"
    echo "Run: docker compose up -d --build --force-recreate inference"
    echo "Then: docker compose restart backend"
    echo "Verify: bash scripts/verify-gpu-passthrough.sh"
  else
    if [[ -f "$OVERRIDE_FILE" ]]; then
      rm -f "$OVERRIDE_FILE"
      echo "Removed $OVERRIDE_FILE (NVIDIA Container Toolkit not configured)."
    fi
    echo "WARNING: NVIDIA GPU detected but NVIDIA Container Toolkit does not appear configured." >&2
    echo "Install: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html" >&2
    echo "Then run: sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker" >&2
    echo "Re-run: bash scripts/configure-gpu-compose.sh" >&2
    exit 1
  fi
else
  if [[ -f "$OVERRIDE_FILE" ]]; then
    rm -f "$OVERRIDE_FILE"
    echo "No NVIDIA GPU detected. Removed $OVERRIDE_FILE."
  else
    echo "No NVIDIA GPU detected. Using default compose stack (AMD/Intel/CPU)."
  fi
fi
