#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OVERRIDE_FILE="docker-compose.override.yml"
TEMPLATE_FILE="docker-compose.override.nvidia.yml"

has_nvidia_gpu() {
  if [[ -e /dev/nvidia0 ]]; then
    return 0
  fi
  if command -v nvidia-smi >/dev/null 2>&1; then
    if nvidia-smi -L 2>/dev/null | grep -q 'GPU '; then
      return 0
    fi
  fi
  return 1
}

has_nvidia_toolkit() {
  if docker info 2>/dev/null | grep -qi 'nvidia'; then
    return 0
  fi
  if command -v nvidia-ctk >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

write_override() {
  {
    echo "# Auto-generated by scripts/configure-gpu-compose.sh — do not edit"
    tail -n +2 "$TEMPLATE_FILE"
  } >"$OVERRIDE_FILE"
}

if has_nvidia_gpu; then
  if has_nvidia_toolkit; then
    if [[ ! -f "$TEMPLATE_FILE" ]]; then
      echo "ERROR: Missing $TEMPLATE_FILE" >&2
      exit 1
    fi
    write_override
    echo "NVIDIA GPU detected. Wrote $OVERRIDE_FILE for GPU passthrough."
    echo "Run: docker compose up -d --build"
  else
    if [[ -f "$OVERRIDE_FILE" ]]; then
      rm -f "$OVERRIDE_FILE"
      echo "Removed $OVERRIDE_FILE (NVIDIA Container Toolkit not configured)."
    fi
    echo "WARNING: NVIDIA GPU detected but NVIDIA Container Toolkit does not appear configured." >&2
    echo "Install: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html" >&2
    echo "Then run: sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker" >&2
    echo "Re-run: bash scripts/configure-gpu-compose.sh" >&2
    exit 1
  fi
else
  if [[ -f "$OVERRIDE_FILE" ]]; then
    rm -f "$OVERRIDE_FILE"
    echo "No NVIDIA GPU detected. Removed $OVERRIDE_FILE."
  else
    echo "No NVIDIA GPU detected. Using default compose stack (AMD/Intel/CPU)."
  fi
fi
