#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OVERRIDE_FILE="docker-compose.override.yml"
TEMPLATE_FILE="docker-compose.override.nvidia.yml"
QUIET=0

log_info() {
  if [[ "$QUIET" -eq 0 ]]; then
    echo "$@"
  fi
}

log_warn() {
  echo "WARNING: $*" >&2
}

log_error() {
  echo "ERROR: $*" >&2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --quiet)
      QUIET=1
      shift
      ;;
    -h | --help)
      echo "Usage: $0 [--quiet]"
      echo "Auto-configure docker-compose.override.yml for NVIDIA GPU passthrough."
      echo "Normally invoked by ./lmpanel; run manually for diagnostics."
      exit 0
      ;;
    *)
      log_error "Unknown option: $1"
      exit 1
      ;;
  esac
done

run_with_timeout() {
  local seconds="$1"
  shift
  if command -v timeout >/dev/null 2>&1; then
    timeout "$seconds" "$@"
  else
    "$@"
  fi
}

has_nvidia_gpu() {
  if [[ -e /dev/nvidia0 ]]; then
    return 0
  fi
  if command -v nvidia-smi >/dev/null 2>&1; then
    if run_with_timeout 5 nvidia-smi -L 2>/dev/null | grep -q 'GPU '; then
      return 0
    fi
  fi
  return 1
}

has_nvidia_toolkit() {
  if run_with_timeout 10 docker info 2>/dev/null | grep -qi 'nvidia'; then
    return 0
  fi
  if command -v nvidia-ctk >/dev/null 2>&1; then
    return 0
  fi
  return 1
}

host_has_vulkan_icd() {
  for icd in /usr/share/vulkan/icd.d/nvidia_icd.json /etc/vulkan/icd.d/nvidia_icd.json; do
    [[ -f "$icd" ]] && return 0
  done
  return 1
}

write_override_content() {
  {
    echo "# Auto-generated by scripts/configure-gpu-compose.sh — do not edit"
    tail -n +2 "$TEMPLATE_FILE"
  }
}

write_override_if_changed() {
  local tmp
  tmp="$(mktemp)"
  write_override_content >"$tmp"
  if [[ -f "$OVERRIDE_FILE" ]] && cmp -s "$tmp" "$OVERRIDE_FILE"; then
    rm -f "$tmp"
    return 1
  fi
  mv "$tmp" "$OVERRIDE_FILE"
  return 0
}

remove_override_if_present() {
  if [[ -f "$OVERRIDE_FILE" ]]; then
    rm -f "$OVERRIDE_FILE"
    return 0
  fi
  return 1
}

write_override() {
  if ! host_has_vulkan_icd; then
    log_warn "nvidia_icd.json not found on host."
    log_warn "Install the NVIDIA driver with Vulkan support for GPU inference."
    log_warn "LmPanel will still start; Vulkan may not work until the driver is fixed."
  fi

  if write_override_if_changed; then
    log_info "NVIDIA GPU detected. Wrote $OVERRIDE_FILE for GPU passthrough."
    log_info "AMD/Intel GPUs remain available via /dev/dri for mixed-vendor hosts."
    log_info "Run: ./lmpanel up --build --force-recreate inference"
    log_info "Then: ./lmpanel restart backend"
    log_info "Verify: bash scripts/verify-gpu-passthrough.sh"
  else
    log_info "NVIDIA GPU detected. $OVERRIDE_FILE is already up to date."
  fi
}

if has_nvidia_gpu; then
  if has_nvidia_toolkit; then
    if [[ ! -f "$TEMPLATE_FILE" ]]; then
      log_error "Missing $TEMPLATE_FILE"
      exit 1
    fi
    write_override
  else
    if remove_override_if_present; then
      log_info "Removed $OVERRIDE_FILE (NVIDIA Container Toolkit not configured)."
    fi
    log_error "NVIDIA GPU detected but NVIDIA Container Toolkit does not appear configured."
    log_error "Install: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html"
    log_error "Then run: sudo nvidia-ctk runtime configure --runtime=docker && sudo systemctl restart docker"
    log_error "Re-run: ./lmpanel up"
    exit 1
  fi
else
  if remove_override_if_present; then
    log_info "No NVIDIA GPU detected. Removed $OVERRIDE_FILE."
  else
    log_info "No NVIDIA GPU detected. Using default compose stack (AMD/Intel/CPU)."
  fi
fi
